# frozen_string_literal: true

source "https://rubygems.org"

gemspec

group :development, :test do
  gem "rake", "~> 13.0"
  gem "rspec", "~> 3.12"
  gem "webmock", "~> 3.19"
  gem "vcr", "~> 6.2"
  gem "timecop", "~> 0.9"
  gem "rack", "~> 3.0"
  gem "rack-test", "~> 2.1"
end
